#!/bin/bash

# Signs the macOS code files (executables, shared objects, dynlibs) that were
# generated by PyInstaller.

appBundleName="PyQtPopupDemo"
appFldrName=PyQtPopupDemo
exeName=PyQtPopupDemo

echo
echo "Enter the path to the folder containing the PyInstaller app build."
echo "Leave blank to use the default location:"
defBuildLoc=`pwd`/dist
echo $defBuildLoc
read -p "Path: " appBuildPath

[[ -z $appBuildPath ]] && appBuildPath=$defBuildLoc
if [[ ${appBuildPath:0:2} == '~/' ]]; then
    appBuildPath="${HOME}${appBuildPath:1}"
fi

echo
echo "Enter the path to the entitlements file, 'entitlements.plist'."
echo "Leave blank to use the default location:"
defEntLoc=`pwd`
echo $defEntLoc
read -p "Path: " entFilePath

[[ -z $entFilePath ]] && entFilePath=$defEntLoc
if [[ ${entFilePath:0:2} == '~/' ]]; then
    entFilePath="${HOME}${entFilePath:1}"
fi
entFilePath="${entFilePath}/entitlements.plist"

echo
echo "Enter the name of your Apple Developer ID Application signing identity."
echo "This should start with \"Developer ID Application: ...\""
read -p "Name: " devIDApp

tsOpt=''
echo
read -p "Add timestamp to signed code? (Y/N): " addTimestamp

[[ $addTimestamp == "Y" || $addTimestamp == "y" ]] && tsOpt='--timestamp'

echo
echo "Starting code signing..."
echo

cd "dist/${appBundleName}.app/Contents/Frameworks"
echo -n "Code signing: "
pwd
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd PySide6
codesign -s "${devIDApp}" --force $tsOpt *.so
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd Qt/lib
codesign -s "${devIDApp}" --force $tsOpt *.framework
cd ../plugins/generic
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../imageformats
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../iconengines
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../platforms
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../styles
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../networkinformation
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../platforminputcontexts
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../tls
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../../../../  # dist/${appBundleName}.app/Contents/Frameworks
codesign -s "${devIDApp}" --force $tsOpt Python.framework
cd python3.14/lib-dynload
codesign -s "${devIDApp}" --force $tsOpt *.so
cd ../../  # dist/${appBundleName}.app/Contents/Frameworks
cd ./shiboken6
codesign -s "${devIDApp}" --force $tsOpt *.so
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../../../../  # dist
pwd
echo

cd $appFldrName/_internal
echo -n "Now code signing: "
pwd
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd PySide6
codesign -s "${devIDApp}" --force $tsOpt *.so
cd Qt/lib
codesign -s "${devIDApp}" --force $tsOpt *.framework
cd ../plugins/generic
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../imageformats
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../iconengines
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../platforms
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../styles
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../networkinformation
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../platforminputcontexts
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../tls
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../../../../  # dist/${appBundleName}.app/Contents/Frameworks
codesign -s "${devIDApp}" --force $tsOpt Python.framework
cd python3.14/lib-dynload
codesign -s "${devIDApp}" --force $tsOpt *.so
cd ../../  # dist/${appBundleName}.app/Contents/Frameworks
cd ./shiboken6
codesign -s "${devIDApp}" --force $tsOpt *.so
codesign -s "${devIDApp}" --force $tsOpt *.dylib
cd ../../../  # dist
pwd
cd $appFldrName
echo
echo -n "Code signing executable located at: "
pwd
codesign -s "${devIDApp}" --force $tsOpt -o runtime --entitlements $entFilePath $exeName

cd ../  # dist
echo
echo -n "Code signing main app bundle located at: "
pwd
codesign -s "${devIDApp}" --force $tsOpt -o runtime --entitlements $entFilePath "${appBundleName}.app"

if [[ $? -ne 0 ]]; then
    echo
    echo "Code signing failed.  Check the above error messages."
    echo
    exit 1
fi

echo
echo "Code signing complete."
echo
# END
